MASKDIR=..

.PHONY: findRookMagics
rfind: findRookMagics.cpp $(MASKDIR)/masks.hpp
	$(CC) -o rfind findRookMagics.cpp

.PHONY: findBishopMagics
bfind: findBishopMagics.cpp $(MASKDIR)/masks.hpp
	$(CC) -o bfind findBishopMagics.cpp
